package com.prodigalgal.xaigateway.admin.api;

import com.prodigalgal.xaigateway.gateway.core.interop.CapabilityResolutionView;
import com.prodigalgal.xaigateway.gateway.core.catalog.SurfaceCapabilityView;
import com.prodigalgal.xaigateway.gateway.core.shared.AuthStrategy;
import com.prodigalgal.xaigateway.gateway.core.shared.ErrorSchemaStrategy;
import com.prodigalgal.xaigateway.gateway.core.shared.ExecutionBackend;
import com.prodigalgal.xaigateway.gateway.core.shared.ModelAddressingStrategy;
import com.prodigalgal.xaigateway.gateway.core.shared.PathStrategy;
import com.prodigalgal.xaigateway.gateway.core.shared.ProviderFamily;
import com.prodigalgal.xaigateway.gateway.core.shared.SiteProfileSource;
import com.prodigalgal.xaigateway.gateway.core.shared.UpstreamSiteKind;
import java.time.Instant;
import java.util.List;
import java.util.Map;

public record ProviderSiteResponse(
        Long id,
        String profileCode,
        String displayName,
        String vendorCode,
        String vendorName,
        ProviderFamily providerFamily,
        UpstreamSiteKind siteKind,
        AuthStrategy authStrategy,
        PathStrategy pathStrategy,
        ModelAddressingStrategy modelAddressingStrategy,
        ErrorSchemaStrategy errorSchemaStrategy,
        String baseUrlPattern,
        String description,
        Map<String, Object> conversationProfile,
        SiteProfileSource profileSource,
        boolean active,
        String healthState,
        String blockedReason,
        List<String> supportedProtocols,
        String compatibilitySurface,
        List<String> credentialRequirements,
        List<ProviderProtocolEndpointResponse> protocolEndpoints,
        String streamTransport,
        String fallbackStrategy,
        int cooldownCredentialCount,
        Instant cooldownUntil,
        long linkedCredentialCount,
        boolean hasSnapshot,
        ExecutionBackend preferredBackend,
        List<ExecutionBackend> supportedBackends,
        Map<String, CapabilityResolutionView> features,
        Map<String, SurfaceCapabilityView> surfaces,
        int modelCount,
        Instant refreshedAt,
        Instant createdAt,
        Instant updatedAt
) {
    public ProviderSiteResponse(
            Long id,
            String profileCode,
            String displayName,
            ProviderFamily providerFamily,
            UpstreamSiteKind siteKind,
            AuthStrategy authStrategy,
            PathStrategy pathStrategy,
            ModelAddressingStrategy modelAddressingStrategy,
            ErrorSchemaStrategy errorSchemaStrategy,
            String baseUrlPattern,
            String description,
            SiteProfileSource profileSource,
            boolean active,
            String healthState,
            String blockedReason,
            List<String> supportedProtocols,
            String compatibilitySurface,
            List<String> credentialRequirements,
            List<ProviderProtocolEndpointResponse> protocolEndpoints,
            String streamTransport,
            String fallbackStrategy,
            int cooldownCredentialCount,
            Instant cooldownUntil,
            long linkedCredentialCount,
            boolean hasSnapshot,
            Map<String, CapabilityResolutionView> features,
            Map<String, SurfaceCapabilityView> surfaces,
            int modelCount,
            Instant refreshedAt,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(
                id,
                profileCode,
                displayName,
                null,
                null,
                providerFamily,
                siteKind,
                authStrategy,
                pathStrategy,
                modelAddressingStrategy,
                errorSchemaStrategy,
                baseUrlPattern,
                description,
                Map.of(),
                profileSource,
                active,
                healthState,
                blockedReason,
                supportedProtocols,
                compatibilitySurface,
                credentialRequirements,
                protocolEndpoints,
                streamTransport,
                fallbackStrategy,
                cooldownCredentialCount,
                cooldownUntil,
                linkedCredentialCount,
                hasSnapshot,
                features,
                surfaces,
                modelCount,
                refreshedAt,
                createdAt,
                updatedAt
        );
    }

    public ProviderSiteResponse(
            Long id,
            String profileCode,
            String displayName,
            String vendorCode,
            String vendorName,
            ProviderFamily providerFamily,
            UpstreamSiteKind siteKind,
            AuthStrategy authStrategy,
            PathStrategy pathStrategy,
            ModelAddressingStrategy modelAddressingStrategy,
            ErrorSchemaStrategy errorSchemaStrategy,
            String baseUrlPattern,
            String description,
            Map<String, Object> conversationProfile,
            SiteProfileSource profileSource,
            boolean active,
            String healthState,
            String blockedReason,
            List<String> supportedProtocols,
            String compatibilitySurface,
            List<String> credentialRequirements,
            List<ProviderProtocolEndpointResponse> protocolEndpoints,
            String streamTransport,
            String fallbackStrategy,
            int cooldownCredentialCount,
            Instant cooldownUntil,
            long linkedCredentialCount,
            boolean hasSnapshot,
            Map<String, CapabilityResolutionView> features,
            Map<String, SurfaceCapabilityView> surfaces,
            int modelCount,
            Instant refreshedAt,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(
                id,
                profileCode,
                displayName,
                vendorCode,
                vendorName,
                providerFamily,
                siteKind,
                authStrategy,
                pathStrategy,
                modelAddressingStrategy,
                errorSchemaStrategy,
                baseUrlPattern,
                description,
                conversationProfile,
                profileSource,
                active,
                healthState,
                blockedReason,
                supportedProtocols,
                compatibilitySurface,
                credentialRequirements,
                protocolEndpoints,
                streamTransport,
                fallbackStrategy,
                cooldownCredentialCount,
                cooldownUntil,
                linkedCredentialCount,
                hasSnapshot,
                ExecutionBackend.SPRING_AI,
                List.of(ExecutionBackend.SPRING_AI),
                features,
                surfaces,
                modelCount,
                refreshedAt,
                createdAt,
                updatedAt
        );
    }
}
